// Utility functions to load mock data on-demand instead of defining inline in components
// This reduces initial bundle size and improves load times

interface TaxonomyRule {
  key: string;
  category: string;
  criteria: string;
  threshold: string;
  evidenceRequired: string;
}

interface ProjectClassification {
  key: string;
  projectId: string;
  projectName: string;
  sector: string;
  classification: "Green" | "Transition" | "Not Green";
  evidenceStatus: "Provided" | "Missing";
  evidenceFile?: string;
  lastUpdated: string;
}

interface CarbonData {
  key: string;
  projectId: string;
  projectName: string;
  sector: string;
  scope1: number; // tCO₂e
  scope2: number; // tCO₂e
  scope3: number; // tCO₂e
  total: number; // tCO₂e
  baselineYear: number;
  baselineEmissions: number; // tCO₂e
  targetYear: number;
  targetReduction: number; // percentage
  currentProgress: number; // percentage
  status: "On Track" | "At Risk" | "Off Track";
}

interface PFISubmission {
  key: string;
  pfiName: string;
  projectId: string;
  submissionDate: string;
  status: "Draft" | "Submitted" | "Validated" | "Approved" | "Published";
  dataQualityScore: number;
  errorCount: number;
  validator: string;
  lastUpdated: string;
}

interface ErrorLog {
  key: string;
  field: string;
  issue: string;
  rowId: string;
  severity: "Critical" | "Warning" | "Info";
  status: "Open" | "Resolved";
  action: string;
}

export const getMockTaxonomyRules = (): TaxonomyRule[] => {
  return [
    {
      key: "1",
      category: "Renewable Energy",
      criteria: "Projects generating energy from renewable sources",
      threshold: "≥80% renewable energy output",
      evidenceRequired: "Energy generation reports, renewable source certificates",
    },
    {
      key: "2",
      category: "Energy Efficiency",
      criteria: "Projects reducing energy consumption",
      threshold: "≥30% energy reduction vs baseline",
      evidenceRequired: "Energy audits, baseline comparison reports",
    },
    {
      key: "3",
      category: "Clean Transportation",
      criteria: "Electric or low-emission transport systems",
      threshold: "Zero direct emissions or <50g CO₂/km",
      evidenceRequired: "Vehicle specifications, emission certificates",
    },
    {
      key: "4",
      category: "Water & Wastewater",
      criteria: "Water conservation and treatment projects",
      threshold: "≥20% water savings or treatment capacity ≥10,000 m³/day",
      evidenceRequired: "Water impact assessments, treatment certifications",
    },
    {
      key: "5",
      category: "Waste Management",
      criteria: "Recycling, composting, or waste-to-energy",
      threshold: "≥60% waste diversion from landfill",
      evidenceRequired: "Waste audit reports, diversion certificates",
    },
    {
      key: "6",
      category: "Transition Activities",
      criteria: "Activities in transition towards green",
      threshold: "Meets transition pathway criteria",
      evidenceRequired: "Transition plans, improvement commitments",
    },
  ];
};

export const getMockClassifications = (): ProjectClassification[] => {
  return [
    {
      key: "1",
      projectId: "PROJ-2024-001",
      projectName: "Lagos Solar Farm Initiative",
      sector: "Renewable Energy",
      classification: "Green",
      evidenceStatus: "Provided",
      evidenceFile: "solar_farm_evidence.pdf",
      lastUpdated: "2024-01-20",
    },
    {
      key: "2",
      projectId: "PROJ-2024-002",
      projectName: "Kano Water Treatment Plant",
      sector: "Water & Sanitation",
      classification: "Green",
      evidenceStatus: "Provided",
      evidenceFile: "water_treatment_evidence.pdf",
      lastUpdated: "2024-01-18",
    },
    {
      key: "3",
      projectId: "PROJ-2024-003",
      projectName: "Port Harcourt Refinery Upgrade",
      sector: "Oil & Gas",
      classification: "Transition",
      evidenceStatus: "Provided",
      evidenceFile: "refinery_transition_plan.pdf",
      lastUpdated: "2024-01-15",
    },
    {
      key: "4",
      projectId: "PROJ-2024-004",
      projectName: "Abuja Metro Rail Extension",
      sector: "Transportation",
      classification: "Green",
      evidenceStatus: "Provided",
      evidenceFile: "metro_rail_evidence.pdf",
      lastUpdated: "2024-01-22",
    },
    {
      key: "5",
      projectId: "PROJ-2024-005",
      projectName: "Kaduna Coal Power Plant",
      sector: "Energy",
      classification: "Not Green",
      evidenceStatus: "Missing",
      lastUpdated: "2024-01-10",
    },
    {
      key: "6",
      projectId: "PROJ-2024-006",
      projectName: "Enugu Waste Management Facility",
      sector: "Waste Management",
      classification: "Green",
      evidenceStatus: "Provided",
      evidenceFile: "waste_management_evidence.pdf",
      lastUpdated: "2024-01-25",
    },
    {
      key: "7",
      projectId: "PROJ-2024-007",
      projectName: "Ibadan Wind Energy Project",
      sector: "Renewable Energy",
      classification: "Green",
      evidenceStatus: "Provided",
      evidenceFile: "wind_energy_evidence.pdf",
      lastUpdated: "2024-01-19",
    },
    {
      key: "8",
      projectId: "PROJ-2024-008",
      projectName: "Benin City Water Supply Upgrade",
      sector: "Water & Sanitation",
      classification: "Green",
      evidenceStatus: "Provided",
      evidenceFile: "water_supply_evidence.pdf",
      lastUpdated: "2024-01-17",
    },
    {
      key: "9",
      projectId: "PROJ-2024-009",
      projectName: "Warri Refinery Modernization",
      sector: "Oil & Gas",
      classification: "Transition",
      evidenceStatus: "Provided",
      evidenceFile: "warri_refinery_transition.pdf",
      lastUpdated: "2024-01-14",
    },
    {
      key: "10",
      projectId: "PROJ-2024-0010",
      projectName: "Lagos BRT System Expansion",
      sector: "Transportation",
      classification: "Green",
      evidenceStatus: "Provided",
      evidenceFile: "brt_expansion_evidence.pdf",
      lastUpdated: "2024-01-23",
    },
    {
      key: "11",
      projectId: "PROJ-2024-0011",
      projectName: "Kano Gas Power Station",
      sector: "Energy",
      classification: "Transition",
      evidenceStatus: "Provided",
      evidenceFile: "gas_power_transition.pdf",
      lastUpdated: "2024-01-16",
    },
    {
      key: "12",
      projectId: "PROJ-2024-0012",
      projectName: "Port Harcourt Recycling Plant",
      sector: "Waste Management",
      classification: "Green",
      evidenceStatus: "Provided",
      evidenceFile: "recycling_plant_evidence.pdf",
      lastUpdated: "2024-01-21",
    },
    {
      key: "13",
      projectId: "PROJ-2024-0013",
      projectName: "Jos Solar Microgrid",
      sector: "Renewable Energy",
      classification: "Green",
      evidenceStatus: "Provided",
      evidenceFile: "solar_microgrid_evidence.pdf",
      lastUpdated: "2024-01-24",
    },
    {
      key: "14",
      projectId: "PROJ-2024-0014",
      projectName: "Calabar Industrial Waste Treatment",
      sector: "Waste Management",
      classification: "Green",
      evidenceStatus: "Provided",
      evidenceFile: "industrial_waste_evidence.pdf",
      lastUpdated: "2024-01-20",
    },
    {
      key: "15",
      projectId: "PROJ-2024-0015",
      projectName: "Kaduna Oil Refinery Expansion",
      sector: "Oil & Gas",
      classification: "Not Green",
      evidenceStatus: "Missing",
      lastUpdated: "2024-01-12",
    },
  ];
};

export const getMockCarbonData = (): CarbonData[] => {
  return [
    {
      key: "1",
      projectId: "PROJ-2024-001",
      projectName: "Lagos Solar Farm Initiative",
      sector: "Renewable Energy",
      scope1: 150,
      scope2: 450,
      scope3: 2300,
      total: 2900,
      baselineYear: 2023,
      baselineEmissions: 5000,
      targetYear: 2026,
      targetReduction: 45,
      currentProgress: 42,
      status: "On Track",
    },
    {
      key: "2",
      projectId: "PROJ-2024-002",
      projectName: "Kano Water Treatment Plant",
      sector: "Water & Sanitation",
      scope1: 280,
      scope2: 1200,
      scope3: 4200,
      total: 5680,
      baselineYear: 2023,
      baselineEmissions: 7000,
      targetYear: 2025,
      targetReduction: 30,
      currentProgress: 19,
      status: "On Track",
    },
    {
      key: "3",
      projectId: "PROJ-2024-003",
      projectName: "Port Harcourt Refinery Upgrade",
      sector: "Oil & Gas",
      scope1: 4500,
      scope2: 2800,
      scope3: 15000,
      total: 22300,
      baselineYear: 2023,
      baselineEmissions: 28000,
      targetYear: 2027,
      targetReduction: 25,
      currentProgress: 20,
      status: "At Risk",
    },
    {
      key: "4",
      projectId: "PROJ-2024-004",
      projectName: "Abuja Metro Rail Extension",
      sector: "Transportation",
      scope1: 120,
      scope2: 800,
      scope3: 5200,
      total: 6120,
      baselineYear: 2023,
      baselineEmissions: 8000,
      targetYear: 2026,
      targetReduction: 35,
      currentProgress: 24,
      status: "On Track",
    },
    {
      key: "5",
      projectId: "PROJ-2024-005",
      projectName: "Kaduna Coal Power Plant",
      sector: "Energy",
      scope1: 8500,
      scope2: 3200,
      scope3: 12000,
      total: 23700,
      baselineYear: 2023,
      baselineEmissions: 26000,
      targetYear: 2026,
      targetReduction: 15,
      currentProgress: 9,
      status: "Off Track",
    },
    {
      key: "6",
      projectId: "PROJ-2024-006",
      projectName: "Enugu Waste Management Facility",
      sector: "Waste Management",
      scope1: 180,
      scope2: 520,
      scope3: 2800,
      total: 3500,
      baselineYear: 2023,
      baselineEmissions: 5500,
      targetYear: 2025,
      targetReduction: 40,
      currentProgress: 36,
      status: "On Track",
    },
    {
      key: "7",
      projectId: "PROJ-2024-007",
      projectName: "Ibadan Wind Energy Project",
      sector: "Renewable Energy",
      scope1: 120,
      scope2: 380,
      scope3: 2100,
      total: 2600,
      baselineYear: 2023,
      baselineEmissions: 4800,
      targetYear: 2026,
      targetReduction: 48,
      currentProgress: 46,
      status: "On Track",
    },
    {
      key: "8",
      projectId: "PROJ-2024-008",
      projectName: "Benin City Water Supply Upgrade",
      sector: "Water & Sanitation",
      scope1: 220,
      scope2: 950,
      scope3: 3800,
      total: 4970,
      baselineYear: 2023,
      baselineEmissions: 6800,
      targetYear: 2025,
      targetReduction: 32,
      currentProgress: 27,
      status: "On Track",
    },
    {
      key: "9",
      projectId: "PROJ-2024-009",
      projectName: "Warri Refinery Modernization",
      sector: "Oil & Gas",
      scope1: 5200,
      scope2: 3200,
      scope3: 18000,
      total: 26400,
      baselineYear: 2023,
      baselineEmissions: 32000,
      targetYear: 2027,
      targetReduction: 22,
      currentProgress: 18,
      status: "At Risk",
    },
    {
      key: "10",
      projectId: "PROJ-2024-0010",
      projectName: "Lagos BRT System Expansion",
      sector: "Transportation",
      scope1: 95,
      scope2: 650,
      scope3: 4800,
      total: 5545,
      baselineYear: 2023,
      baselineEmissions: 7500,
      targetYear: 2026,
      targetReduction: 38,
      currentProgress: 26,
      status: "On Track",
    },
    {
      key: "11",
      projectId: "PROJ-2024-0011",
      projectName: "Kano Gas Power Station",
      sector: "Energy",
      scope1: 3800,
      scope2: 2100,
      scope3: 9500,
      total: 15400,
      baselineYear: 2023,
      baselineEmissions: 20000,
      targetYear: 2026,
      targetReduction: 28,
      currentProgress: 23,
      status: "On Track",
    },
    {
      key: "12",
      projectId: "PROJ-2024-0012",
      projectName: "Port Harcourt Recycling Plant",
      sector: "Waste Management",
      scope1: 140,
      scope2: 480,
      scope3: 2400,
      total: 3020,
      baselineYear: 2023,
      baselineEmissions: 5200,
      targetYear: 2025,
      targetReduction: 45,
      currentProgress: 42,
      status: "On Track",
    },
    {
      key: "13",
      projectId: "PROJ-2024-0013",
      projectName: "Jos Solar Microgrid",
      sector: "Renewable Energy",
      scope1: 80,
      scope2: 250,
      scope3: 1200,
      total: 1530,
      baselineYear: 2023,
      baselineEmissions: 3200,
      targetYear: 2025,
      targetReduction: 55,
      currentProgress: 52,
      status: "On Track",
    },
    {
      key: "14",
      projectId: "PROJ-2024-0014",
      projectName: "Calabar Industrial Waste Treatment",
      sector: "Waste Management",
      scope1: 200,
      scope2: 680,
      scope3: 3200,
      total: 4080,
      baselineYear: 2023,
      baselineEmissions: 6000,
      targetYear: 2026,
      targetReduction: 35,
      currentProgress: 32,
      status: "On Track",
    },
    {
      key: "15",
      projectId: "PROJ-2024-0015",
      projectName: "Kaduna Oil Refinery Expansion",
      sector: "Oil & Gas",
      scope1: 9200,
      scope2: 3800,
      scope3: 14000,
      total: 27000,
      baselineYear: 2023,
      baselineEmissions: 30000,
      targetYear: 2027,
      targetReduction: 12,
      currentProgress: 10,
      status: "Off Track",
    },
  ];
};

export const getMockPFISubmissions = (): PFISubmission[] => {
  return [
    {
      key: "1",
      pfiName: "Lagos Solar Farm Initiative",
      projectId: "PROJ-2024-001",
      submissionDate: "2024-01-20",
      status: "Approved",
      dataQualityScore: 95,
      errorCount: 2,
      validator: "John Doe",
      lastUpdated: "2024-01-22",
    },
    {
      key: "2",
      pfiName: "Kano Water Treatment Plant",
      projectId: "PROJ-2024-002",
      submissionDate: "2024-01-18",
      status: "Validated",
      dataQualityScore: 88,
      errorCount: 5,
      validator: "Jane Smith",
      lastUpdated: "2024-01-21",
    },
    {
      key: "3",
      pfiName: "Port Harcourt Refinery Upgrade",
      projectId: "PROJ-2024-003",
      submissionDate: "2024-01-15",
      status: "Submitted",
      dataQualityScore: 72,
      errorCount: 12,
      validator: "-",
      lastUpdated: "2024-01-16",
    },
    {
      key: "4",
      pfiName: "Abuja Metro Rail Extension",
      projectId: "PROJ-2024-004",
      submissionDate: "2024-01-25",
      status: "Published",
      dataQualityScore: 92,
      errorCount: 1,
      validator: "John Doe",
      lastUpdated: "2024-01-26",
    },
    {
      key: "5",
      pfiName: "Kaduna Coal Power Plant",
      projectId: "PROJ-2024-005",
      submissionDate: "2024-01-10",
      status: "Draft",
      dataQualityScore: 45,
      errorCount: 28,
      validator: "-",
      lastUpdated: "2024-01-12",
    },
    {
      key: "6",
      pfiName: "Enugu Waste Management Facility",
      projectId: "PROJ-2024-006",
      submissionDate: "2024-01-22",
      status: "Approved",
      dataQualityScore: 89,
      errorCount: 3,
      validator: "Jane Smith",
      lastUpdated: "2024-01-24",
    },
    {
      key: "7",
      pfiName: "Ibadan Wind Energy Project",
      projectId: "PROJ-2024-007",
      submissionDate: "2024-01-19",
      status: "Approved",
      dataQualityScore: 93,
      errorCount: 1,
      validator: "John Doe",
      lastUpdated: "2024-01-21",
    },
    {
      key: "8",
      pfiName: "Benin City Water Supply Upgrade",
      projectId: "PROJ-2024-008",
      submissionDate: "2024-01-17",
      status: "Validated",
      dataQualityScore: 87,
      errorCount: 4,
      validator: "Jane Smith",
      lastUpdated: "2024-01-20",
    },
    {
      key: "9",
      pfiName: "Warri Refinery Modernization",
      projectId: "PROJ-2024-009",
      submissionDate: "2024-01-14",
      status: "Submitted",
      dataQualityScore: 68,
      errorCount: 15,
      validator: "-",
      lastUpdated: "2024-01-15",
    },
    {
      key: "10",
      pfiName: "Lagos BRT System Expansion",
      projectId: "PROJ-2024-0010",
      submissionDate: "2024-01-23",
      status: "Published",
      dataQualityScore: 91,
      errorCount: 2,
      validator: "John Doe",
      lastUpdated: "2024-01-25",
    },
    {
      key: "11",
      pfiName: "Kano Gas Power Station",
      projectId: "PROJ-2024-0011",
      submissionDate: "2024-01-16",
      status: "Validated",
      dataQualityScore: 75,
      errorCount: 8,
      validator: "Jane Smith",
      lastUpdated: "2024-01-18",
    },
    {
      key: "12",
      pfiName: "Port Harcourt Recycling Plant",
      projectId: "PROJ-2024-0012",
      submissionDate: "2024-01-21",
      status: "Approved",
      dataQualityScore: 90,
      errorCount: 2,
      validator: "John Doe",
      lastUpdated: "2024-01-23",
    },
    {
      key: "13",
      pfiName: "Jos Solar Microgrid",
      projectId: "PROJ-2024-0013",
      submissionDate: "2024-01-24",
      status: "Published",
      dataQualityScore: 94,
      errorCount: 1,
      validator: "Jane Smith",
      lastUpdated: "2024-01-26",
    },
    {
      key: "14",
      pfiName: "Calabar Industrial Waste Treatment",
      projectId: "PROJ-2024-0014",
      submissionDate: "2024-01-20",
      status: "Validated",
      dataQualityScore: 86,
      errorCount: 5,
      validator: "John Doe",
      lastUpdated: "2024-01-22",
    },
    {
      key: "15",
      pfiName: "Kaduna Oil Refinery Expansion",
      projectId: "PROJ-2024-0015",
      submissionDate: "2024-01-12",
      status: "Draft",
      dataQualityScore: 52,
      errorCount: 32,
      validator: "-",
      lastUpdated: "2024-01-13",
    },
  ];
};

export const getMockErrorLog = (): ErrorLog[] => {
  return [
    {
      key: "1",
      field: "Carbon Scope 1",
      issue: "Missing emission factor for diesel consumption",
      rowId: "PROJ-2024-003-001",
      severity: "Critical",
      status: "Open",
      action: "Require emission factor input",
    },
    {
      key: "2",
      field: "ESG Compliance Status",
      issue: "Incomplete evidence documentation",
      rowId: "PROJ-2024-003-002",
      severity: "Warning",
      status: "Open",
      action: "Upload missing documents",
    },
    {
      key: "3",
      field: "Green Taxonomy Classification",
      issue: "Classification does not match sector criteria",
      rowId: "PROJ-2024-003-003",
      severity: "Critical",
      status: "Open",
      action: "Review and update classification",
    },
    {
      key: "4",
      field: "Project Amount",
      issue: "Value exceeds expected range for sector",
      rowId: "PROJ-2024-003-004",
      severity: "Warning",
      status: "Open",
      action: "Verify data accuracy",
    },
    {
      key: "5",
      field: "Carbon Scope 2",
      issue: "Missing grid emission factor",
      rowId: "PROJ-2024-005-001",
      severity: "Critical",
      status: "Open",
      action: "Provide grid emission factor",
    },
    {
      key: "6",
      field: "End Date",
      issue: "End date is before start date",
      rowId: "PROJ-2024-005-002",
      severity: "Critical",
      status: "Open",
      action: "Correct project timeline",
    },
    {
      key: "7",
      field: "Taxonomy Evidence",
      issue: "Evidence file not uploaded",
      rowId: "PROJ-2024-005-003",
      severity: "Warning",
      status: "Open",
      action: "Upload evidence document",
    },
    {
      key: "8",
      field: "Location",
      issue: "Location field is empty",
      rowId: "PROJ-2024-009-001",
      severity: "Warning",
      status: "Open",
      action: "Provide project location",
    },
    {
      key: "9",
      field: "Carbon Scope 3",
      issue: "Upstream emissions data incomplete",
      rowId: "PROJ-2024-009-002",
      severity: "Warning",
      status: "Open",
      action: "Complete scope 3 emissions data",
    },
    {
      key: "10",
      field: "Data Quality Score",
      issue: "Score below acceptable threshold",
      rowId: "PROJ-2024-0015-001",
      severity: "Critical",
      status: "Open",
      action: "Improve data completeness",
    },
    {
      key: "11",
      field: "Sector Classification",
      issue: "Sector does not match project description",
      rowId: "PROJ-2024-0015-002",
      severity: "Warning",
      status: "Resolved",
      action: "Updated sector classification",
    },
    {
      key: "12",
      field: "Project Start Date",
      issue: "Date format incorrect",
      rowId: "PROJ-2024-0011-001",
      severity: "Info",
      status: "Resolved",
      action: "Corrected date format",
    },
    {
      key: "13",
      field: "ESG Status",
      issue: "Status workflow violation",
      rowId: "PROJ-2024-0011-002",
      severity: "Warning",
      status: "Open",
      action: "Review approval workflow",
    },
    {
      key: "14",
      field: "Beneficiary Count",
      issue: "Value missing",
      rowId: "PROJ-2024-009-003",
      severity: "Warning",
      status: "Open",
      action: "Provide beneficiary count",
    },
    {
      key: "15",
      field: "Energy Consumption",
      issue: "Units not specified",
      rowId: "PROJ-2024-005-004",
      severity: "Info",
      status: "Open",
      action: "Specify measurement units",
    },
  ];
};

export const getMockPortfolioData = () => {
  return {
    portfolioValue: 12500000000,
    projectCount: 42,
    esgCompleteness: 87,
    reportingTimeliness: { onTime: 38, late: 4, total: 42 },
    greenTaxonomy: { green: 65, transition: 25, notGreen: 10 },
    carbonSummary: { scope1: 12450, scope2: 8750, scope3: 32100, total: 53300 },
    esgFlags: { red: 3, amber: 7, green: 32 }
  };
};

export const getMockProjects = () => {
  return [
    { projectId: "PROJ-2024-001", pfiName: "Lagos Solar Farm Initiative", sector: "Renewable Energy", location: "Lagos State", amount: 2500000000, taxonomyStatus: "Green", esgStatus: "Complete" },
    { projectId: "PROJ-2024-002", pfiName: "Kano Water Treatment Plant", sector: "Water & Sanitation", location: "Kano State", amount: 1800000000, taxonomyStatus: "Green", esgStatus: "Complete" },
    { projectId: "PROJ-2024-003", pfiName: "Port Harcourt Refinery Upgrade", sector: "Oil & Gas", location: "Rivers State", amount: 4500000000, taxonomyStatus: "Transition", esgStatus: "Incomplete" },
    { projectId: "PROJ-2024-004", pfiName: "Abuja Metro Rail Extension", sector: "Transportation", location: "FCT, Abuja", amount: 3200000000, taxonomyStatus: "Green", esgStatus: "Complete" },
    { projectId: "PROJ-2024-005", pfiName: "Kaduna Coal Power Plant", sector: "Energy", location: "Kaduna State", amount: 3800000000, taxonomyStatus: "Not Green", esgStatus: "Incomplete" },
    { projectId: "PROJ-2024-006", pfiName: "Enugu Waste Management Facility", sector: "Waste Management", location: "Enugu State", amount: 950000000, taxonomyStatus: "Green", esgStatus: "Complete" },
    { projectId: "PROJ-2024-007", pfiName: "Ibadan Wind Energy Project", sector: "Renewable Energy", location: "Oyo State", amount: 2200000000, taxonomyStatus: "Green", esgStatus: "Complete" },
    { projectId: "PROJ-2024-008", pfiName: "Benin City Water Supply Upgrade", sector: "Water & Sanitation", location: "Edo State", amount: 1450000000, taxonomyStatus: "Green", esgStatus: "Complete" },
    { projectId: "PROJ-2024-009", pfiName: "Warri Refinery Modernization", sector: "Oil & Gas", location: "Delta State", amount: 5200000000, taxonomyStatus: "Transition", esgStatus: "Incomplete" },
    { projectId: "PROJ-2024-0010", pfiName: "Lagos BRT System Expansion", sector: "Transportation", location: "Lagos State", amount: 2800000000, taxonomyStatus: "Green", esgStatus: "Complete" },
    { projectId: "PROJ-2024-0011", pfiName: "Kano Gas Power Station", sector: "Energy", location: "Kano State", amount: 3500000000, taxonomyStatus: "Transition", esgStatus: "Incomplete" },
    { projectId: "PROJ-2024-0012", pfiName: "Port Harcourt Recycling Plant", sector: "Waste Management", location: "Rivers State", amount: 1200000000, taxonomyStatus: "Green", esgStatus: "Complete" },
    { projectId: "PROJ-2024-0013", pfiName: "Jos Solar Microgrid", sector: "Renewable Energy", location: "Plateau State", amount: 850000000, taxonomyStatus: "Green", esgStatus: "Complete" },
    { projectId: "PROJ-2024-0014", pfiName: "Calabar Industrial Waste Treatment", sector: "Waste Management", location: "Cross River State", amount: 1650000000, taxonomyStatus: "Green", esgStatus: "Complete" },
    { projectId: "PROJ-2024-0015", pfiName: "Kaduna Oil Refinery Expansion", sector: "Oil & Gas", location: "Kaduna State", amount: 4800000000, taxonomyStatus: "Not Green", esgStatus: "Incomplete" },
  ];
};